### ISSUE TITLE
Add switcherSecret and serviceCode in IntegrationUpdate POJO class

### ISSUE THREAD

**Issue by brijeshpatel1610** [zendesk/sunshine-conversations-java#11]
Smooch has added new fields like switcherSecret and serviceCode into IntegrationCreate POJO class, but not added into IntegrationUpdate POJO class.

Please add new fields into IntegrationUpdate POJO class as well.

**Comment by alavers** [comment]
Thanks for the bug report! We'll get this fixed

**Comment by b0uh** [comment]
Hello @brijeshpatel1610,

Sorry for the delay, we just released a new version (5.7.0) with both `switcherSecret` and `serviceCode` in the `IntegrationUpdate` class.

If something is wrong please let us know.
