### ISSUE TITLE
Can't delete AppUser property

### ISSUE THREAD

**Issue by corby** [zendesk/sunshine-conversations-java#16]
There doesn't seem to be a way to delete a property from the AppUser object.
The docs say set the key to delete to null, but when you do the following:
```
AppUserUpdate upd = new AppUserUpdate().properties(Collections.singletonMap(key, null));
apiAppUser.updateAppUser(id, userId, upd);
```
won't do anything at all because the GSON serializer will remove null parameters from the map before serializing them into the body.

There doesn't seem to be a way around this other than calling the REST API directly.

**Comment by spasiu** [comment]
@corby, **unfortunately**, this is a result of our Swagger 2 code gen. But **fortunately**, we're currently working on a v2 API and a new API lib w/ code gen using Open API 3. This problem should be fixed and custom props will be nullable. Expect this at the end of September.
