### ISSUE TITLE
Get my message notification when sending message.

### ISSUE THREAD

**Issue by ghost** [zendesk/sunshine-conversations-java#2]
I'm using both `smooch-api` and `smooch-android` in my Android app. When sending message using `smooch-java` `ConversationApi.postMessage()`, my app displays a notification which is my message and `smooch-android` `Conversation.getUnreadCount()` return a `count` which includes my message.

How could I hide / disable the notification and exclude the message from `Conversation.getUnreadCount()` ?

**Comment by DataWearsAHood** [comment]
Doing some cleanup - if you're still seeing this issue with the latest versions, feel free to reopen the issue.
