### ISSUE TITLE
Smooch Upload Attachment API Doesn't works with doc,csv,log,yaml,yml,eml,basic.ics,mpga,neon,vcf,mp4a extensions

### ISSUE THREAD

**Issue by ahnaidu** [zendesk/sunshine-conversations-java#31]
Smooch Upload Attachment API generates exception "io.smooch.client.ApiException: Unsupported Media Type" on uploading file having extension as "doc,csv,log,yaml,yml,eml,basic.ics,mpga,neon,vcf,mp4a".

Details:
-----------------
File : AttachmentsApi.java
Method:  public AttachmentResponse uploadAttachment(String appId, File source, String access, String _for, String appUserId, String userId) throws ApiException
jar: api
Version: 5.28.0

Please assist.

**Comment by UlyssesDB** [comment]
We would like to learn more about what specifically your use-case entails, how you're going about testing this, and what impact this is having.

It would be helpful if we could move this conversation to a forum better suited for discussion - I would appreciate if you could pack up any information related to this issue, with any further context you can provide (feel free to reference this Github issue), and submit a ticket to:
[conversations-support@zendesk.com](conversations-support@zendesk.com)

I think we'll be better able to assist you there.
