### ISSUE TITLE
Upgrade com.squareup.okhttp:okhttp to com.squareup.okhttp3:okhttp

### ISSUE THREAD

**Issue by bdeneuter** [zendesk/sunshine-conversations-java#5]
We are using the smooch-sdk together with Spring Platform IO cairo.
The version of selenium-java uses the latest version of com.squareup.okhttp3:okhttp
and conflicts with the versoion of okhttp bundled with the smooch SDK.
To be more precise, the underlying library okio causes the problem and results in a MoSuchMethodException

**Comment by DataWearsAHood** [comment]
Doing some cleanup - if you're still seeing this issue with the latest versions, feel free to reopen the issue.
